sonar.projectKey=4awalk-client
sonar.projectName=4AWalk Client
sonar.host.url=http://localhost:9000
sonar.token=sqa_3e10ca096b6e75f687e742b8e1ba8c888fbf698f

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java,app/src/androidTest/java
# Le chemin des binaires compilés :
sonar.java.binaries=app/build/intermediates/javac/debug/classes

# chemin vers le rapport jacoco :
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

# Rapports de tests unitaires JVM
sonar.junit.reportPaths=app/build/test-results/testDebugUnitTest